environment:
  matrix:
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
    - MSYS2_ARCH: i686
      MSYSTEM: MINGW32

# Set path for msys
init:
  - PATH C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;C:\msys64\bin;%PATH%
  # System upgrade (must be run twice, separately, to finalize). Disabled
  # for now due to build time and resource usage (500MB bw, 2.7GB disk)
  # - bash -lc "/usr/bin/env pacman --noconfirm -Syu"
  # - bash -lc "/usr/bin/env pacman --noconfirm -Syu"

build_script:
  - bash '%APPVEYOR_BUILD_FOLDER%\appveyor.sh'

deploy: off
